# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/112QDqAUa_X5_NDLi8sGxI8Q76VL_Eea7
"""

from setuptools import setup, find_packages

setup(
    name="hlapeptide",
    version="0.1",
    packages=find_packages(),
    install_requires=[
        'tensorflow>=2.6',
        'pandas',
        'numpy',
        'torch',
        'fair-esm'
    ],
)